name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # или master, в зависимости от названия вашей основной ветки

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Debug - List dist contents
        run: |
          echo "Contents of dist directory:"
          ls -la dist/
          echo "Contents of dist directory (recursive):"
          find dist/ -type f

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./dist